#!/bin/bash

#Turn on debug-mode
set -x

cd nginx-1.20.0

#Runs the configure script, checks your system for various dependencies and sets up the build configuration
./configure

#make is a tool, which reads the instructions from the Makefile generated by the configure script  
#Compiles the source code and builds the executable binaries for the software
make

#Installs the compiled binaries and any necessary files to their final locations on your system
sudo make install